# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\autod\OneDrive\同步\开发\FFmpeg工具箱\vca\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 774)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 962, 289))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_preset = QtWidgets.QLabel(self.groupBox_5)
        self.lbl_preset.setObjectName("lbl_preset")
        self.gridLayout_2.addWidget(self.lbl_preset, 3, 3, 1, 1)
        self.cbb_encoder = QtWidgets.QComboBox(self.groupBox_5)
        self.cbb_encoder.setObjectName("cbb_encoder")
        self.cbb_encoder.addItem("")
        self.cbb_encoder.addItem("")
        self.cbb_encoder.addItem("")
        self.cbb_encoder.addItem("")
        self.gridLayout_2.addWidget(self.cbb_encoder, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 6, 1, 1, 1)
        self.cbb_fps = QtWidgets.QComboBox(self.groupBox_5)
        self.cbb_fps.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.cbb_fps.setEditable(True)
        self.cbb_fps.setObjectName("cbb_fps")
        self.cbb_fps.addItem("")
        self.cbb_fps.addItem("")
        self.cbb_fps.addItem("")
        self.cbb_fps.addItem("")
        self.cbb_fps.addItem("")
        self.cbb_fps.addItem("")
        self.cbb_fps.addItem("")
        self.cbb_fps.addItem("")
        self.cbb_fps.addItem("")
        self.cbb_fps.addItem("")
        self.cbb_fps.addItem("")
        self.cbb_fps.addItem("")
        self.cbb_fps.addItem("")
        self.gridLayout_2.addWidget(self.cbb_fps, 6, 2, 1, 1)
        self.lbl_crf = QtWidgets.QLabel(self.groupBox_5)
        self.lbl_crf.setObjectName("lbl_crf")
        self.gridLayout_2.addWidget(self.lbl_crf, 4, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 7, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 8, 1, 1, 1)
        self.txt_bitrate_max = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.txt_bitrate_max.setDecimals(1)
        self.txt_bitrate_max.setMaximum(500.0)
        self.txt_bitrate_max.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.txt_bitrate_max.setProperty("value", 20.0)
        self.txt_bitrate_max.setObjectName("txt_bitrate_max")
        self.gridLayout_2.addWidget(self.txt_bitrate_max, 8, 2, 1, 1)
        self.chk_crf = QtWidgets.QCheckBox(self.groupBox_5)
        self.chk_crf.setText("")
        self.chk_crf.setChecked(True)
        self.chk_crf.setObjectName("chk_crf")
        self.gridLayout_2.addWidget(self.chk_crf, 4, 0, 1, 1)
        self.txt_bitrate = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.txt_bitrate.setDecimals(1)
        self.txt_bitrate.setMaximum(500.0)
        self.txt_bitrate.setProperty("value", 10.0)
        self.txt_bitrate.setObjectName("txt_bitrate")
        self.gridLayout_2.addWidget(self.txt_bitrate, 7, 2, 1, 1)
        self.sld_preset = QtWidgets.QSlider(self.groupBox_5)
        self.sld_preset.setMinimum(-5)
        self.sld_preset.setMaximum(3)
        self.sld_preset.setOrientation(QtCore.Qt.Horizontal)
        self.sld_preset.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sld_preset.setObjectName("sld_preset")
        self.gridLayout_2.addWidget(self.sld_preset, 3, 2, 1, 1)
        self.chk_fps = QtWidgets.QCheckBox(self.groupBox_5)
        self.chk_fps.setText("")
        self.chk_fps.setObjectName("chk_fps")
        self.gridLayout_2.addWidget(self.chk_fps, 6, 0, 1, 1)
        self.txt_size = QtWidgets.QLineEdit(self.groupBox_5)
        self.txt_size.setObjectName("txt_size")
        self.gridLayout_2.addWidget(self.txt_size, 5, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 8, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 5, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 7, 1, 1, 1)
        self.chk_bitrate = QtWidgets.QCheckBox(self.groupBox_5)
        self.chk_bitrate.setText("")
        self.chk_bitrate.setObjectName("chk_bitrate")
        self.gridLayout_2.addWidget(self.chk_bitrate, 7, 0, 1, 1)
        self.chk_size = QtWidgets.QCheckBox(self.groupBox_5)
        self.chk_size.setText("")
        self.chk_size.setObjectName("chk_size")
        self.gridLayout_2.addWidget(self.chk_size, 5, 0, 1, 1)
        self.chk_bitrate_max = QtWidgets.QCheckBox(self.groupBox_5)
        self.chk_bitrate_max.setText("")
        self.chk_bitrate_max.setObjectName("chk_bitrate_max")
        self.gridLayout_2.addWidget(self.chk_bitrate_max, 8, 0, 1, 1)
        self.sld_crf = QtWidgets.QSlider(self.groupBox_5)
        self.sld_crf.setMaximum(99)
        self.sld_crf.setOrientation(QtCore.Qt.Horizontal)
        self.sld_crf.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sld_crf.setTickInterval(5)
        self.sld_crf.setObjectName("sld_crf")
        self.gridLayout_2.addWidget(self.sld_crf, 4, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.btn_start = QtWidgets.QPushButton(self.groupBox)
        self.btn_start.setObjectName("btn_start")
        self.verticalLayout.addWidget(self.btn_start)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 2, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout.addWidget(self.groupBox_3, 2, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_output = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_output.setAutoFillBackground(False)
        self.btn_output.setObjectName("btn_output")
        self.gridLayout_3.addWidget(self.btn_output, 1, 2, 1, 1)
        self.btn_input = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_input.setObjectName("btn_input")
        self.gridLayout_3.addWidget(self.btn_input, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.table_input = QtWidgets.QTableWidget(self.groupBox_6)
        self.table_input.setObjectName("table_input")
        self.table_input.setColumnCount(3)
        self.table_input.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_input.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_input.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_input.setHorizontalHeaderItem(2, item)
        self.gridLayout_3.addWidget(self.table_input, 0, 0, 1, 3)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_6, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1101, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.cbb_fps.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FFmpeg工具箱"))
        self.groupBox.setTitle(_translate("MainWindow", "视频"))
        self.groupBox_5.setTitle(_translate("MainWindow", "视频"))
        self.lbl_preset.setText(_translate("MainWindow", "TextLabel"))
        self.cbb_encoder.setItemText(0, _translate("MainWindow", "H.264"))
        self.cbb_encoder.setItemText(1, _translate("MainWindow", "H.265"))
        self.cbb_encoder.setItemText(2, _translate("MainWindow", "VP9"))
        self.cbb_encoder.setItemText(3, _translate("MainWindow", "Copy"))
        self.label_6.setText(_translate("MainWindow", "CRF："))
        self.label_4.setText(_translate("MainWindow", "帧率："))
        self.cbb_fps.setItemText(0, _translate("MainWindow", "10"))
        self.cbb_fps.setItemText(1, _translate("MainWindow", "20"))
        self.cbb_fps.setItemText(2, _translate("MainWindow", "23.976"))
        self.cbb_fps.setItemText(3, _translate("MainWindow", "24"))
        self.cbb_fps.setItemText(4, _translate("MainWindow", "25"))
        self.cbb_fps.setItemText(5, _translate("MainWindow", "29.97"))
        self.cbb_fps.setItemText(6, _translate("MainWindow", "30"))
        self.cbb_fps.setItemText(7, _translate("MainWindow", "48"))
        self.cbb_fps.setItemText(8, _translate("MainWindow", "59.94"))
        self.cbb_fps.setItemText(9, _translate("MainWindow", "60"))
        self.cbb_fps.setItemText(10, _translate("MainWindow", "72"))
        self.cbb_fps.setItemText(11, _translate("MainWindow", "90"))
        self.cbb_fps.setItemText(12, _translate("MainWindow", "144"))
        self.lbl_crf.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "Mbps"))
        self.label_2.setText(_translate("MainWindow", "最大码率"))
        self.label_8.setText(_translate("MainWindow", "Mbps"))
        self.label_3.setText(_translate("MainWindow", "分辨率："))
        self.label_24.setText(_translate("MainWindow", "平均码率:"))
        self.label_23.setText(_translate("MainWindow", "编码："))
        self.label.setText(_translate("MainWindow", "预设："))
        self.btn_start.setText(_translate("MainWindow", "开始转换"))
        self.groupBox_3.setTitle(_translate("MainWindow", "功能3"))
        self.groupBox_2.setTitle(_translate("MainWindow", "视频比较"))
        self.groupBox_6.setTitle(_translate("MainWindow", "输入/输出"))
        self.btn_output.setText(_translate("MainWindow", "浏览.."))
        self.btn_input.setText(_translate("MainWindow", "添加输入.."))
        item = self.table_input.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "输入"))
        item = self.table_input.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "输入"))
        item = self.table_input.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "状态"))
